# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["ask.svn.io"]
description = "Ask SvN."
language = "javascript"
manifest_version = 2
name = "SVN Ask"
service_id = "Uxza6SQaRliLQPPT1LLtn0"

[scripts]
  build = "npm run build"

[local_server]
  [local_server.backends]
    [local_server.backends.vercel]
      url = "https://api.svn.sh"
      override_host = "api.svn.sh"
